"""
Remove part "AC" from .wig file and .size file generated by gem-2-wig program
"""

import sys
import argparse

parser = argparse.ArgumentParser(description='Process size and wig files.')
parser.add_argument('-w', '--wig', required=True, help='wig file')
parser.add_argument('-s', '--size', required=True, help='size file')
args = vars(parser.parse_args())
wig_fn = args['wig']
size_fn = args['size']

f = open(wig_fn + ".trim.tsv", "w")
for line in open(wig_fn):
    tmp = line.strip().split("\t")
    tmp1 = tmp[1].split(" ")
    f.write("\t".join(tmp[0:1] + tmp1[0:1] + tmp[2:3]) + "\n")
f.close()

f = open(size_fn + ".trim.tsv", "w")
for line in open(size_fn):
    tmp = line.strip().split("\t")
    tmp1 = tmp[0].split(" ")
    f.write("\t".join(tmp1[0:1] + tmp[1:2]) + "\n")
f.close()

