"""
Filter VCF output file generated by Mutect2
"""

import sys
import argparse

parser = argparse.ArgumentParser(description='Modify purecn input files.')
parser.add_argument('-i', '--input_vcf', type=str, required=True, help='purecn input vcf file')
parser.add_argument('-o', '--output_vcf', type=str, required=True, help='filtered output vcf file')
args = vars(parser.parse_args())
input_fn = args['input_vcf']
output_fn = args['output_vcf']

f1 = open(input_fn)
f2 = open(output_fn, "w")
for line in f1:
    if line[0:6] == "#CHROM":
        f2.write("##filtering_status_gdc=\"These calls have been run through GDC-filtration pipeline without PureCN NormalDB (PureCN skipped)\">\n")
        f2.write(line)
    else:
        f2.write(line)
f2.close()
f1.close()
