#!/usr/bin/env python3
"""
Filter VCF output file generated by VarDict in paired calling
"""

import gzip
import os

import click

from gdc_tosvc_tools.__main__ import CLI
from gdc_tosvc_tools.utils import get_info


@click.command(cls=CLI)
@click.option(
    "-i", "--input_vcf", type=str, required=True, help="VarDict input vcf file"
)
@click.option(
    "-o", "--output_vcf", type=str, required=True, help="Filtered output vcf file"
)
def main(
    input_vcf: str,
    output_vcf: str,
) -> None:
    if os.path.basename(input_vcf).endswith(".gz"):
        open_fn = gzip.open
    else:
        open_fn = open  # type: ignore

    filter_add = False
    line: str
    with open_fn(input_vcf) as input_fh, open(output_vcf, "w") as output_fh:
        for line in input_fh:  # type: ignore
            if line.startswith("#"):
                if not filter_add:
                    output_fh.writelines(
                        [
                            '##FILTER=<ID=PASS,Description="Pass all GDC filtering">',
                            '##FILTER=<ID=af0.08,Description="alternative allele frequency (AF) less than 0.08">',
                            '##FILTER=<ID=ssf0.005,Description="p-value of variant (SSF) greater than 0.005">',
                            '##FILTER=<ID=ssf0.0001msi,Description="p-value of variant (SSF) greater than 0.0001 and MSILEN equal to 1 and MSI greater than 4">',
                        ]
                    )
                    filter_add = True
                output_fh.write(line)
                continue

            val = line.strip().split("\t")
            info, sinfo = get_info(val[7:])
            filter_set = []
            if val[6] != "." and val[6] != "PASS":
                filter_set = val[6].split(";")
            try:
                if float(sinfo["AF"]) < 0.08:
                    filter_set.append("f0.08")
            except Exception:
                pass
            try:
                if float(info["SSF"]) > 0.005:
                    filter_set.append("P0.005")
            except Exception:
                pass
            try:
                if (
                    float(info["SSF"]) > 0.0001
                    and float(info["MSI"]) == 1
                    and float(info["MSILEN"]) >= 5
                ):
                    filter_set.append("P0.0001MSI")
            except Exception:
                pass
            if len(filter_set) == 0:
                output_fh.write("\t".join(val[0:6] + ["PASS"] + val[7:]))
                output_fh.write("\n")
            else:
                output_fh.write("\t".join(val[0:6] + [";".join(filter_set)] + val[7:]))
                output_fh.write("\n")


if __name__ == "__main__":
    main()

# __END__
