"""
Remove part "AC" from .wig file and .size file generated by gem-2-wig program
"""

import click


def trim_wig_file(wig_file: str) -> None:
    trimmed_wig_file = f"{wig_file}.trim.tsv"
    with open(wig_file, "r") as wig_fh, open(trimmed_wig_file, "w") as trim_fh:
        for line in wig_fh:
            tmp = line.strip().split("\t")
            tmp1 = tmp[1].split(" ")
            trim_fh.write("\t".join(tmp[0:1] + tmp1[0:1] + tmp[2:3]))
            trim_fh.write("\n")


def trim_size_file(size_file: str) -> None:
    trimmed_size_file = f"{size_file}.trim.tsv"
    with open(trimmed_size_file, "w") as trimmed_fh, open(size_file, "r") as size_fh:
        for line in size_fh:
            tmp = line.strip().split("\t")
            tmp1 = tmp[0].split(" ")
            trimmed_fh.write("\t".join(tmp1[0:1] + tmp[1:2]))
            trimmed_fh.write("\n")


@click.command()
@click.option("--wig", "-w", required=True, help="WIG file")
@click.option("--size", "-s", required=True, help="Size file")
def main(
    wig: str,
    size: str,
) -> None:

    trim_wig_file(wig)
    trim_size_file(size)


if __name__ == "__main__":
    main()

# __END__
